baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hadrien Ferlin'
theme = 'typo'

[params]
description = "Mon site personel"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroContent = """
# Salut
Content de te voir sur mon incroyable site.

Moi c'est Hadrien Ferlin, en ce moment je suis actuellement étudiant en MPI au Lycée Thiers à Marseille.

Je suis l'admin de [OKLM](https://oklm.dev), où j'héberge des services décentralisés vu que c'est sympa (et important) le web ouvert et décentralisé.
"""

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = false


# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "livres"
url = "/livres"

[[params.menu]]
name = "blog"
url = "/blog"

[[params.menu]]
name = "contacts"
url = "/contacts"

[[params.menu]]
name = "à propos"
url = "/a_propos"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'
[markup.goldmark.renderer]
unsafe= true

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
